spring.application.name=payment-engine

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_engine}
spring.datasource.username=${DB_USERNAME:payment_user}
spring.datasource.password=${DB_PASSWORD:payment_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.aws.region=${AWS_REGION:us-east-1}
app.sqs.endpoint=${SQS_ENDPOINT:http://localhost:9324}
app.sqs.queue-url=${SQS_QUEUE_URL:http://localhost:9324/000000000000/payment-processing}

app.outbox.publisher.enabled=${OUTBOX_PUBLISHER_ENABLED:false}
app.outbox.publisher.delay-ms=${OUTBOX_PUBLISHER_DELAY_MS:1000}

app.sqs.consumer-enabled=${SQS_CONSUMER_ENABLED:false}
app.sqs.consumer-poll-delay-ms=1000