include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

aws {
  region = us-east-1
  accountId = 000000000000
}

queues {
  "payment-processing" {
    defaultVisibilityTimeout = 3 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds

    deadLettersQueue {
      name = "payment-processing-dlq"
      maxReceiveCount = 3
    }
  }

  "payment-processing-dlq" {
  }
}